---
id: dokku-201908
base_name: dokku-201908
tags:
- linux
presentation_date: 2019/08/23
version: 2019.08.23.1
licenses: []
slideshare_id: dokku-165791253
speaker_deck_id: dokku-falseshao-jie
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
